export const dummyDeliveryRecruitment = [
  {
    id: 1,
    restaurant: '여우골 서교점',
    menu: '연어 세트',
    timer: 2,
    recruited: 3,
    recruit: 4,
    cost: 12800,
    recruiter: '마이멜로디',
    foodtype: 'japanese',
    building: '한우리집',
    participants: ['폼폼푸린', '토니토니쵸파'],
    content: '함께 드실 분',
    account: 123456,
    status: [0, 1, 2],
  },
  {
    id: 2,
    restaurant: 'BBQ 신촌점',
    menu: '황금올리브치킨',
    timer: 5,
    recruited: 2,
    recruit: 3,
    cost: 8500,
    recruiter: '이화',
    foodtype: 'franchise',
    building: '이하우스',
    participants: ['이화연', '배꽃'],
    content: '함께 드실 분',
    account: 123456,
    status: [0, 1, 2],
  },
  {
    id: 3,
    restaurant: '신촌 족발중독',
    menu: '불족발 大',
    timer: 20,
    recruited: 1,
    recruit: 4,
    cost: 16000,
    recruiter: '토니토니쵸파',
    foodtype: 'korean',
    building: '학생문화관',
    participants: ['피카츄'],
    content: '족발 시키실 분',
    account: 789101112,
    status: [0, 1],
  },
  {
    id: 4,
    restaurant: '파체리토',
    menu: '타코세트',
    timer: 8,
    recruited: 1,
    recruit: 2,
    cost: 16000,
    recruiter: '폼폼푸린',
    foodtype: 'western',
    building: '중앙도서관',
    participants: ['라이츄'],
    content: 'ㅈㄱㄴ',
    account: 4645615189485,
    status: [0, 2],
  },
  {
    id: 5,
    restaurant: '소림마라 마포점',
    menu: '로제마라샹궈 + 꿔바로우',
    timer: 15,
    recruited: 1,
    recruit: 3,
    cost: 14000,
    recruiter: '나몰빼미',
    foodtype: 'franchise',
    building: '한우리집',
    participants: ['파이리'],
    content: '기다려요',
    account: 565681151515,
    status: [0, 1],
  },
  {
    id: 6,
    restaurant: '김밥천국 신촌점',
    menu: '자율 메뉴 선택',
    timer: 28,
    recruited: 0,
    recruit: 3,
    cost: 11000,
    recruiter: '피카츄',
    foodtype: 'korean',
    building: '교외',
    participants: [null],
    content: '족발 시키실 분',
    account: 789101112,
    status: [0],
  },
];
